<?php

namespace Database\Seeders;

class Products 
{
    public static $dbProducts = null; 
    public static $names = [
        1 => [
            'Apple',
            'Orange',
            'Banana',
            'Mango',
            'Grapes',
            'Watermelon',
            'Pineapple',
            'Strawberry',
            'Blueberry',
            'Raspberry',
            'Kiwi',
            'Papaya',
            'Peach',
            'Cherry',
            'Pomegranate',
            'Pear',
            'Guava',
            'Plum',
            'Lychee',
            'Dragonfruit',
            'Apricot',
            'Fig',
            'Coconut',
            'Lemon',
            'Lime',
            'Cranberry',
            'Blackcurrant',
            'Passionfruit',
            'Tangerine',
            'Avocado',
        ],
        2 => [
            'Carrot',
            'Broccoli',
            'Spinach',
            'Cauliflower',
            'Potato',
            'Tomato',
            'Cucumber',
            'Zucchini',
            'Bell Pepper',
            'Lettuce',
            'Cabbage',
            'Onion',
            'Garlic',
            'Eggplant',
            'Asparagus',
            'Peas',
            'Radish',
            'Beetroot',
            'Celery',
            'Kale',
            'Turnip',
            'Sweet Potato',
            'Leek',
            'Pumpkin',
            'Artichoke',
            'Okra',
            'Brussels Sprouts',
            'Chili Pepper',
            'Corn',
            'Mushroom',
            'Parsnip',
            'Swiss Chard',
            'Green Beans',
            'Spring Onion',
            'Fenugreek',
            'Bok Choy',
            'Watercress',
            'Fennel',
            'Dandelion Greens',
        ],
        3 => [
            'Milk',
            'Cheese',
            'Butter',
            'Yogurt',
            'Cream',
            'Buttermilk',
            'Ghee',
            'Paneer',
            'Curd',
            'Sour Cream',
            'Whipped Cream',
            'Ice Cream',
            'Cottage Cheese',
            'Cream Cheese',
            'Condensed Milk',
            'Evaporated Milk',
            'Powdered Milk',
            'Kefir',
            'Mozzarella',
        ],
        4 => [
            'Chicken',
            'Beef',
            'Pork',
            'Lamb',
            'Turkey',
            'Duck',
            'Goat',
            'Venison',
            'Rabbit',
            'Bacon',
            'Sausage',
            'Ham',
            'Salami',
            'Meatballs',
            'Steak',
            'Ground Beef',
            'Pork Chops',
            'Chicken Wings',
            'Chicken Breast',
            'Ribs',
        ],
        5 => [
            'Shrimp',
            'Crab',
            'Lobster',
            'Salmon',
            'Tuna',
            'Cod',
            'Halibut',
            'Mackerel',
            'Sardines',
            'Tilapia',
            'Trout',
            'Oysters',
            'Clams',
            'Scallops',
            'Mussels',
            'Squid',
            'Octopus',
            'Crawfish',
            'Anchovies',
            'Swordfish',
        ],
        6 => [
            'Bread',
            'Baguette',
            'Croissant',
            'Muffin',
            'Doughnut',
            'Danish Pastry',
            'Scone',
            'Biscuit',
            'Bagel',
            'Ciabatta',
            'Focaccia',
            'Brioche',
            'English Muffin',
            'Pretzel',
            'Pita Bread',
            'Cupcake',
            'Brownie',
            'Cheesecake',
            'Éclair',
            'Tart',
            'Pound Cake',
            'Cinnamon Roll',
            'Macaron',
            'Shortbread',
            'Pavlova',
        ],
        7 => [
            'Pureed Carrots',
            'Pureed Sweet Potatoes',
            'Apple Sauce',
            'Mashed Bananas',
            'Pureed Peas',
            'Rice Cereal',
            'Oatmeal Cereal',
            'Mixed Vegetable Puree',
            'Pureed Chicken',
            'Yogurt Melts',
            'Teething Biscuits',
            'Mashed Avocado',
            'Lentil Puree',
        ],
        8 => [
            'Frozen Fish Fillets',
            'Frozen Mixed Vegetables',
            'Frozen Onion Rings',
            'Frozen Pancakes',
            'Frozen Peas',
            'Frozen Pies',
            'Frozen Pineapple Chunks',
            'Frozen Pizza',
            'Frozen Sausages',
            'Frozen Scallops',
            'Frozen Shrimp',
            'Frozen Smoothie Packs',
            'Frozen Soups',
            'Frozen Spinach',
            'Frozen Spring Rolls',
            'Frozen Stir-Fry Mix',
            'Frozen Sushi',
            'Frozen Sweet Potatoes',
            'Frozen Waffles',
        ],
        9 => [
            'Chips',
            'Popcorn',
            'Trail Mix',
            'Granola Bars',
            'Crackers',
            'Cookies',
            'Cheese Sticks',
            'Fruit Snacks',
            'Jerky',
            'Rice Cakes',
            'Potato Wedges',
            'Nachos',
            'Pita Chips',
            'Veggie Sticks',
            'Hummus Dip',
            'Chocolate Bars',
            'Energy Bars',
            'Candy',
            'Ice Cream Bars',
            'Yogurt Parfaits',
            'Bagel Chips',
            'Nuts',
            'Hazelnuts',
            'Corn Nuts',
            'Cheese Puffs',
            'Peanut Butter Cups',
        ],
        10 => [
            'Rice',
            'Pasta',
            'Flour',
            'Sugar',
            'Salt',
            'Cooking Oil',
            'Vinegar',
            'Soy Sauce',
            'Honey',
            'Peanut Butter',
            'Jams',
            'Jellies',
            'Spices',
            'Herbs',
            'Coffee',
            'Tea',
            'Hot Chocolate Mix',
            'Canned Beans',
            'Canned Soups',
            'Canned Tomatoes',
            'Canned Tuna',
            'Cereal',
            'Oats',
            'Baking Powder',
            'Yeast',
            'Instant Noodles',
            'Ketchup',
            'Mustard',
            'Salad Dressings',
            'Pickles',
            'Tomato Paste',
            'Canned Corn',
            'Olive Oil',
            'Breadcrumbs',
            'Mayonnaise',
            'Chili Sauce',
            'Barbecue Sauce',
            'Cornmeal',
            'Stock Cubes',
        ]
    ];
}
